import React, { useState } from 'react';
import { apiClient } from '../api';

const Monetization = () => {
  return (
    <div className="flex-1 flex flex-col items-center justify-center p-8 h-full">
      <div className="glass-panel p-12 max-w-3xl w-full text-center border-t-4 border-cyan-500 bg-cyan-900/10">
        <h1 className="text-3xl font-bold tracking-widest text-cyan-400 mb-6">EARLY DEVELOPMENT ACCESS</h1>
        
        <p className="text-gray-300 font-mono mb-8 text-lg">
          Welcome to the Simulated Singularity C2.
        </p>
        
        <div className="bg-black/50 p-6 border border-gray-800 text-left space-y-4">
          <p className="text-gray-400">
            <span className="text-emerald-400 font-bold">› STATUS: </span>
            Usage is completely free and unlimited during the early development phase.
          </p>
          <p className="text-gray-400">
            <span className="text-purple-400 font-bold">› TELEMETRY: </span>
            All data generated by the autonomous Swarm is saved to the local database and can be used for diagnostics or improving the service.
          </p>
          <p className="text-gray-400">
            <span className="text-cyan-400 font-bold">› AUTONOMY: </span>
            The system is running with zero HITL (Human-in-the-Loop) bottlenecks. Agents autonomously handle all anomalies by prompting the appropriate model authorities.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Monetization;
